// variables
@port = 3000
@baseUrl = http://localhost:{{port}}


// Get all blogs
GET {{baseUrl}}/api/blogs

###
// Post a new blogs
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "title": "Test no author",
    "url": "fail.org"
}

###
DELETE {{baseUrl}}/api/blogs/61b3c44484db40e1b4abf92b

###
DELETE {{baseUrl}}/api/blogs/fail

###
PUT {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "id": "61b3ceb6e1d98f6a8c1fd5dd",
    "title": "Update",
    "author": "Brad Miller",
    "url": "https://runestone.academy/runestone/books/published/pythonds/index.html"
}