// variables
@port = 3000
@baseUrl = http://localhost:{{port}}


// Get all blogs
GET {{baseUrl}}/api/blogs

###
// Post a new blogs
POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbnVzIiwiaWQiOiI2MWI1NjgxMjIxYjc5YjA1ZjdkZmFkY2EiLCJpYXQiOjE2Mzk1OTE5MTV9.qnosEPy9vtvVVWTbF6vN3KYUFPZG37ryWWPu7-rfW4A

{
    "title": "JWT Bearer token authentication",
    "url": "https://medium.com/ms-club-of-sliit/jwt-bearer-token-authentication-for-express-js-5e95bf4dead0",
    "author": "Dinuwan Kalubowila"
}

###
DELETE {{baseUrl}}/api/blogs/61b3c44484db40e1b4abf92b

###
DELETE {{baseUrl}}/api/blogs/fail

###
PUT {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "id": "61b3ceb6e1d98f6a8c1fd5dd",
    "title": "Update",
    "author": "Brad Miller",
    "url": "https://runestone.academy/runestone/books/published/pythonds/index.html"
}